#pragma once

#include "RetroArch\anti-aliasing\shaders\aa-shader-4.0-level2\AntiAliasingShadersAaShader40Level2AaShader40Level2Pass1ShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\aa-shader-4.0-level2\AntiAliasingShadersAaShader40Level2AaShader40Level2Pass2ShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\AntiAliasingShadersAaShader40ShaderDef.h"
#include "RetroArch\sharpen\shaders\SharpenShadersAdaptiveSharpenShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\AntiAliasingShadersAdvancedAaShaderDef.h"
#include "RetroArch\stock\StockStockShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\AntiAliasingShadersFxaaShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\AntiAliasingShadersReverseAaShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\smaa\AntiAliasingShadersSmaaSmaaEdgeDetectionShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\smaa\AntiAliasingShadersSmaaSmaaBlendWeightCalculationShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\smaa\AntiAliasingShadersSmaaSmaaNeighborhoodBlendingShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseLinearizeShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseKawase0ShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseKawase1ShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseKawase2ShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseKawase3ShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseDelinearizeShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseKawase4ShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseKawase5ShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseKawase6ShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseKawase7ShaderDef.h"
#include "RetroArch\blurs\kawase\BlursKawaseScreen_combineShaderDef.h"
#include "RetroArch\cel\shaders\CelShadersAdvcartoonShaderDef.h"
#include "RetroArch\cel\shaders\MMJ_Cel\CelShadersMMJ_CelMMJ_Cel_ShaderShaderDef.h"
#include "RetroArch\cel\shaders\MMJ_Cel\CelShadersMMJ_CelMMJ_Cel_Shader_MP_Blur_HShaderDef.h"
#include "RetroArch\cel\shaders\MMJ_Cel\CelShadersMMJ_CelMMJ_Cel_Shader_MP_Blur_VShaderDef.h"
#include "RetroArch\cel\shaders\MMJ_Cel\CelShadersMMJ_CelMMJ_Cel_Shader_MP_OutlineShaderDef.h"
#include "RetroArch\cel\shaders\MMJ_Cel\CelShadersMMJ_CelMMJ_Cel_Shader_MP_ColorShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtApertureShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtCaligariShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtCgwgFastShaderDef.h"
#include "RetroArch\crt\shaders\crt-easymode-halation\CrtShadersCrtEasymodeHalationLinearizeShaderDef.h"
#include "RetroArch\crt\shaders\crt-easymode-halation\CrtShadersCrtEasymodeHalationBlur_horizShaderDef.h"
#include "RetroArch\crt\shaders\crt-easymode-halation\CrtShadersCrtEasymodeHalationBlur_vertShaderDef.h"
#include "RetroArch\crt\shaders\crt-easymode-halation\CrtShadersCrtEasymodeHalationThresholdShaderDef.h"
#include "RetroArch\crt\shaders\crt-easymode-halation\CrtShadersCrtEasymodeHalationCrtEasymodeHalationShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtEasymodeShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtFrutbunnShaderDef.h"
#include "RetroArch\crt\shaders\geom-deluxe\CrtShadersGeomDeluxePhosphor_applyShaderDef.h"
#include "RetroArch\crt\shaders\geom-deluxe\CrtShadersGeomDeluxePhosphor_updateShaderDef.h"
#include "RetroArch\crt\shaders\geom-deluxe\CrtShadersGeomDeluxeGaussxShaderDef.h"
#include "RetroArch\crt\shaders\geom-deluxe\CrtShadersGeomDeluxeGaussyShaderDef.h"
#include "RetroArch\crt\shaders\geom-deluxe\CrtShadersGeomDeluxeCrtGeomDeluxeShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtGeomShaderDef.h"
#include "RetroArch\crt\shaders\guest\lut\CrtShadersGuestLutLutShaderDef.h"
#include "RetroArch\crt\shaders\guest\fast\CrtShadersGuestFastSmoothingShaderDef.h"
#include "RetroArch\crt\shaders\guest\fast\CrtShadersGuestFastLinearizeMultipassShaderDef.h"
#include "RetroArch\crt\shaders\guest\fast\CrtShadersGuestFastCrtGuestDrVenomPass1ShaderDef.h"
#include "RetroArch\crt\shaders\guest\fast\CrtShadersGuestFastCrtGuestDrVenomPass2ShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestColorProfilesShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestD65D50ShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestAfterglowShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestAvgLumShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestLinearizeShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestBlur_horizShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestBlur_vertShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestLinearize_scanlinesShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestCrtGuestDrVenomShaderDef.h"
#include "RetroArch\crt\shaders\guest\crt-sm\CrtShadersGuestCrtSmD65D50SmShaderDef.h"
#include "RetroArch\crt\shaders\guest\crt-sm\CrtShadersGuestCrtSmCrtGuestSmRot0ShaderDef.h"
#include "RetroArch\crt\shaders\guest\crt-sm\CrtShadersGuestCrtSmLinearizeSmShaderDef.h"
#include "RetroArch\crt\shaders\guest\crt-sm\CrtShadersGuestCrtSmBlur_horizSmShaderDef.h"
#include "RetroArch\crt\shaders\guest\crt-sm\CrtShadersGuestCrtSmBlur_vertSmShaderDef.h"
#include "RetroArch\crt\shaders\guest\crt-sm\CrtShadersGuestCrtSmCrtGuestSmShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtHyllian3dShaderDef.h"
#include "RetroArch\crt\shaders\glow\CrtShadersGlowLinearizeShaderDef.h"
#include "RetroArch\crt\shaders\crt-hyllian-glow\CrtShadersCrtHyllianGlowCrtHyllianShaderDef.h"
#include "RetroArch\crt\shaders\glow\CrtShadersGlowThresholdShaderDef.h"
#include "RetroArch\crt\shaders\glow\CrtShadersGlowBlur_horizShaderDef.h"
#include "RetroArch\crt\shaders\glow\CrtShadersGlowBlur_vertShaderDef.h"
#include "RetroArch\crt\shaders\crt-hyllian-glow\CrtShadersCrtHyllianGlowResolve2ShaderDef.h"
#include "RetroArch\crt\shaders\crt-hyllian-multipass\CrtShadersCrtHyllianMultipassCrtHyllianPass0ShaderDef.h"
#include "RetroArch\crt\shaders\crt-hyllian-multipass\CrtShadersCrtHyllianMultipassCrtHyllianPass1ShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtHyllianShaderDef.h"
#include "RetroArch\crt\shaders\crt-interlaced-halation\CrtShadersCrtInterlacedHalationCrtInterlacedHalationPass0ShaderDef.h"
#include "RetroArch\crt\shaders\crt-interlaced-halation\CrtShadersCrtInterlacedHalationCrtInterlacedHalationPass1ShaderDef.h"
#include "RetroArch\crt\shaders\crt-interlaced-halation\CrtShadersCrtInterlacedHalationCrtInterlacedHalationPass2ShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtLottesFastShaderDef.h"
#include "RetroArch\crt\shaders\crt-lottes-multipass\CrtShadersCrtLottesMultipassBloompassShaderDef.h"
#include "RetroArch\crt\shaders\crt-lottes-multipass\CrtShadersCrtLottesMultipassScanpassGlowShaderDef.h"
#include "RetroArch\crt\shaders\glow-trails\CrtShadersGlowTrailsGlowTrails0ShaderDef.h"
#include "RetroArch\blurs\BlursBlur9fastVerticalShaderDef.h"
#include "RetroArch\blurs\BlursBlur9fastHorizontalShaderDef.h"
#include "RetroArch\crt\shaders\glow-trails\CrtShadersGlowTrailsGlowTrails1ShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleFirstPassLinearizeCrtGammaBobFieldsShaderDef.h"
#include "RetroArch\crt\shaders\crt-lottes-multipass\CrtShadersCrtLottesMultipassBloompassGlowShaderDef.h"
#include "RetroArch\crt\shaders\crt-lottes-multipass\CrtShadersCrtLottesMultipassScanpassShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtLottesShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtMattiasShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtNesMiniShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersCrtPiShaderDef.h"
#include "RetroArch\crt\shaders\crt-potato\shader-files\CrtShadersCrtPotatoShaderFilesCrtPotatoShaderDef.h"
#include "RetroArch\crt\shaders\torridgristle\CrtShadersTorridgristleScanlineInterpolationShaderDef.h"
#include "RetroArch\crt\shaders\torridgristle\CrtShadersTorridgristleScanlineSimpleShaderDef.h"
#include "RetroArch\reshade\shaders\blendoverlay\ReshadeShadersBlendoverlayBlendoverlayShaderDef.h"
#include "RetroArch\crt\shaders\torridgristle\CrtShadersTorridgristleBrightenShaderDef.h"
#include "RetroArch\crt\shaders\torridgristle\CrtShadersTorridgristleSunsetGaussianVertShaderDef.h"
#include "RetroArch\crt\shaders\torridgristle\CrtShadersTorridgristleSunsetGaussianHorizShaderDef.h"
#include "RetroArch\crt\shaders\torridgristle\CrtShadersTorridgristleCandyBloomShaderDef.h"
#include "RetroArch\crt\shaders\glow\CrtShadersGlowGauss_horizShaderDef.h"
#include "RetroArch\crt\shaders\glow\CrtShadersGlowGauss_vertShaderDef.h"
#include "RetroArch\crt\shaders\glow\CrtShadersGlowResolveShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass1Composite3phaseShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass23phaseLinearShaderDef.h"
#include "RetroArch\crt\shaders\glow\CrtShadersGlowLanczos_horizShaderDef.h"
#include "RetroArch\crt\shaders\crtsim\CrtShadersCrtsimCompositeShaderDef.h"
#include "RetroArch\crt\shaders\crtsim\CrtShadersCrtsimScreenShaderDef.h"
#include "RetroArch\crt\shaders\crtsim\CrtShadersCrtsimPostDownsampleShaderDef.h"
#include "RetroArch\crt\shaders\crtsim\CrtShadersCrtsimPostUpsampleShaderDef.h"
#include "RetroArch\crt\shaders\crtsim\CrtShadersCrtsimPresentShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersFakelottesShaderDef.h"
#include "RetroArch\crt\shaders\GritsScanlines\CrtShadersGritsScanlinesGritsScanlinesShaderDef.h"
#include "RetroArch\crt\shaders\gtu-v050\CrtShadersGtuV050Pass1ShaderDef.h"
#include "RetroArch\crt\shaders\gtu-v050\CrtShadersGtuV050Pass2ShaderDef.h"
#include "RetroArch\crt\shaders\gtu-v050\CrtShadersGtuV050Pass3ShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_ntsc_encodeShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_ntsc_decodeShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_colorShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_prescaleShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_deconvergeShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_scanlineShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_defocusShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_postShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_phosphorShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_chromaShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersMame_distortionShaderDef.h"
#include "RetroArch\crt\shaders\metacrt\CrtShadersMetacrtBufCShaderDef.h"
#include "RetroArch\crt\shaders\metacrt\CrtShadersMetacrtBufDShaderDef.h"
#include "RetroArch\crt\shaders\metacrt\CrtShadersMetacrtImageShaderDef.h"
#include "RetroArch\crt\shaders\newpixie\CrtShadersNewpixieAccumulateShaderDef.h"
#include "RetroArch\crt\shaders\newpixie\CrtShadersNewpixieBlur_horizShaderDef.h"
#include "RetroArch\crt\shaders\newpixie\CrtShadersNewpixieBlur_vertShaderDef.h"
#include "RetroArch\crt\shaders\newpixie\CrtShadersNewpixieNewpixieCrtShaderDef.h"
#include "RetroArch\crt\shaders\phosphorlut\CrtShadersPhosphorlutScanlinesInterlaceLinearizeShaderDef.h"
#include "RetroArch\blurs\BlursBlur5fastVerticalShaderDef.h"
#include "RetroArch\blurs\BlursBlur5fastHorizontalShaderDef.h"
#include "RetroArch\crt\shaders\phosphorlut\CrtShadersPhosphorlutPhosphorlutPass0ShaderDef.h"
#include "RetroArch\crt\shaders\phosphorlut\CrtShadersPhosphorlutPhosphorlutPass1ShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\old\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersOldShadersMame_hlslShadersMame_ntscShaderDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\shaders\old\shaders\mame_hlsl\shaders\CrtShadersMame_hlslShadersOldShadersMame_hlslShadersMame_colorShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersTvoutTweaksShaderDef.h"
#include "RetroArch\misc\MiscImageAdjustmentShaderDef.h"
#include "RetroArch\blurs\BlursBlur11fastVerticalShaderDef.h"
#include "RetroArch\blurs\BlursBlur11fastHorizontalShaderDef.h"
#include "RetroArch\crt\shaders\glow-trails\CrtShadersGlowTrailsCombineShaderDef.h"
#include "RetroArch\ntsc\shaders\ntsc-adaptive\NtscShadersNtscAdaptiveNtscPass1ShaderDef.h"
#include "RetroArch\ntsc\shaders\ntsc-adaptive\NtscShadersNtscAdaptiveNtscPass2ShaderDef.h"
#include "RetroArch\crt\shaders\vt220\CrtShadersVt220Vt220ShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersYee64ShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersYeetronShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersZfast_crtShaderDef.h"
#include "RetroArch\cubic\shaders\CubicShadersBicubicShaderDef.h"
#include "RetroArch\cubic\shaders\CubicShadersLinearizeShaderDef.h"
#include "RetroArch\cubic\shaders\CubicShadersCubicGammaCorrectShaderDef.h"
#include "RetroArch\cubic\shaders\CubicShadersCubicShaderDef.h"
#include "RetroArch\ddt\shaders\DdtShadersDdtShaderDef.h"
#include "RetroArch\denoisers\shaders\DenoisersShadersFastBilateralShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuperXbrPass0ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuperXbrPass1ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuperXbrPass2ShaderDef.h"
#include "RetroArch\windowed\shaders\WindowedShadersJinc2ShaderDef.h"
#include "RetroArch\denoisers\shaders\DenoisersShadersFastBilateral3dShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper2xbr3dPass0ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper2xbr3dPass1ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper2xbr3dPass2ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuperXbrPass1bShaderDef.h"
#include "RetroArch\misc\MiscNaturalVisionShaderDef.h"
#include "RetroArch\denoisers\shaders\DenoisersShadersMedian_3x3ShaderDef.h"
#include "RetroArch\denoisers\shaders\DenoisersShadersMedian_5x5ShaderDef.h"
#include "RetroArch\denoisers\shaders\DenoisersShadersSlowBilateralShaderDef.h"
#include "RetroArch\dithering\shaders\DitheringShadersBayerMatrixDitheringShaderDef.h"
#include "RetroArch\dithering\shaders\cbod-v1\DitheringShadersCbodV1CbodV1Pass1ShaderDef.h"
#include "RetroArch\dithering\shaders\cbod-v1\DitheringShadersCbodV1CbodV1Pass2ShaderDef.h"
#include "RetroArch\dithering\shaders\gdapt\DitheringShadersGdaptGdaptPass0ShaderDef.h"
#include "RetroArch\dithering\shaders\gdapt\DitheringShadersGdaptGdaptPass1ShaderDef.h"
#include "RetroArch\dithering\shaders\DitheringShadersGenditherShaderDef.h"
#include "RetroArch\dithering\shaders\mdapt\passes\DitheringShadersMdaptPassesMdaptPass0ShaderDef.h"
#include "RetroArch\dithering\shaders\mdapt\passes\DitheringShadersMdaptPassesMdaptPass1ShaderDef.h"
#include "RetroArch\dithering\shaders\mdapt\passes\DitheringShadersMdaptPassesMdaptPass2ShaderDef.h"
#include "RetroArch\dithering\shaders\mdapt\passes\DitheringShadersMdaptPassesMdaptPass3ShaderDef.h"
#include "RetroArch\dithering\shaders\mdapt\passes\DitheringShadersMdaptPassesMdaptPass4ShaderDef.h"
#include "RetroArch\dithering\shaders\ps1dither\DitheringShadersPs1ditherPS1UnditherBoxBlurShaderDef.h"
#include "RetroArch\dithering\shaders\ps1dither\DitheringShadersPs1ditherPS1UnditherAntiBayerShaderDef.h"
#include "RetroArch\dithering\shaders\ps1dither\DitheringShadersPs1ditherPS1UnditherComparisonMkIIShaderDef.h"
#include "RetroArch\eagle\shaders\EagleShadersSupereagleShaderDef.h"
#include "RetroArch\gpu\shaders\3dfx\GpuShaders3dfx3dfx_pass_0ShaderDef.h"
#include "RetroArch\gpu\shaders\3dfx\GpuShaders3dfx3dfx_pass_1ShaderDef.h"
#include "RetroArch\gpu\shaders\3dfx\GpuShaders3dfx3dfx_pass_2ShaderDef.h"
#include "RetroArch\gpu\shaders\GpuShadersPowervr2ShaderDef.h"
#include "RetroArch\gpu\shaders\3dfx\old\GpuShaders3dfxOld3dfx_pass_0ShaderDef.h"
#include "RetroArch\gpu\shaders\3dfx\old\GpuShaders3dfxOld3dfx_pass_1ShaderDef.h"
#include "RetroArch\gpu\shaders\3dfx\old\GpuShaders3dfxOld3dfx_pass_2ShaderDef.h"
#include "RetroArch\hqx\shader-files\HqxShaderFilesHq2xHalphonShaderDef.h"
#include "RetroArch\hqx\shader-files\HqxShaderFilesPass1ShaderDef.h"
#include "RetroArch\hqx\shader-files\HqxShaderFilesHq2xShaderDef.h"
#include "RetroArch\hqx\shader-files\HqxShaderFilesHq3xShaderDef.h"
#include "RetroArch\hqx\shader-files\HqxShaderFilesHq4xShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersAannShaderDef.h"
#include "RetroArch\linear\LinearLinearizeShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersBandlimitPixelShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersControlledSharpnessShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersGridBlendHybridShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersPixellateShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersQuilezShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersSharpBilinearScanlinesShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersSharpBilinearSimpleShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersSharpBilinearShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersSmootheststepShaderDef.h"
#include "RetroArch\interpolation\shaders\InterpolationShadersSmuberStepShaderDef.h"
#include "RetroArch\linear\LinearLinearGammaCorrectShaderDef.h"
#include "RetroArch\misc\MiscImg_modShaderDef.h"
#include "RetroArch\motion-interpolation\shaders\motion_interpolation\MotionInterpolationShadersMotion_interpolationMotion_interpolation_pass0ShaderDef.h"
#include "RetroArch\motion-interpolation\shaders\motion_interpolation\MotionInterpolationShadersMotion_interpolationMotion_interpolation_pass3ShaderDef.h"
#include "RetroArch\motionblur\shaders\MotionblurShadersFeedbackShaderDef.h"
#include "RetroArch\motionblur\shaders\MotionblurShadersMix_framesShaderDef.h"
#include "RetroArch\motionblur\shaders\MotionblurShadersMix_frames_smartShaderDef.h"
#include "RetroArch\motionblur\shaders\MotionblurShadersMotionblurBlueShaderDef.h"
#include "RetroArch\motionblur\shaders\MotionblurShadersMotionblurColorShaderDef.h"
#include "RetroArch\motionblur\shaders\MotionblurShadersMotionblurSimpleShaderDef.h"
#include "RetroArch\motionblur\shaders\MotionblurShadersResponseTimeShaderDef.h"
#include "RetroArch\nedi\shaders\NediShadersNediPass0ShaderDef.h"
#include "RetroArch\nedi\shaders\NediShadersNediPass1ShaderDef.h"
#include "RetroArch\nedi\shaders\NediShadersNediPass2ShaderDef.h"
#include "RetroArch\nedi\shaders\NediShadersNediJincShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\cgwg-famicom-geom\Nes_raw_paletteShadersCgwgFamicomGeomCompositeEncodeShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\cgwg-famicom-geom\Nes_raw_paletteShadersCgwgFamicomGeomLowpassNotchDecodeYiqShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\cgwg-famicom-geom\Nes_raw_paletteShadersCgwgFamicomGeomAdaptiveCombDecodeShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\cgwg-famicom-geom\Nes_raw_paletteShadersCgwgFamicomGeomLowpassChromaShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\cgwg-famicom-geom\Nes_raw_paletteShadersCgwgFamicomGeomCrtGeomFamicomShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\gtu-famicom\Nes_raw_paletteShadersGtuFamicomDAC_LUTShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\gtu-famicom\Nes_raw_paletteShadersGtuFamicomLowPassShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\gtu-famicom\Nes_raw_paletteShadersGtuFamicomCombFilterShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\gtu-famicom\Nes_raw_paletteShadersGtuFamicomScaleXShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\gtu-famicom\Nes_raw_paletteShadersGtuFamicomScaleYShaderDef.h"
#include "RetroArch\nes_raw_palette\shaders\Nes_raw_paletteShadersNesColorDecoderShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass23phaseShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersRgbToYuvShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns16Win8x4Pass1LumaShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns16Win8x4Pass2LumaShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersJinc2CshiftLumaShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersJinc2OnPassoutput0ShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersYuvToRgb2xShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns16Win8x4Pass1RgbShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns16Win8x4Pass2RgbShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersJinc2CshiftRgbShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersYuvToRgb4xShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns32Win8x4Pass1RgbShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns32Win8x4Pass2RgbShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns32Win8x4Pass1LumaShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns32Win8x4Pass2LumaShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersJinc2OnPassoutput3ShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns64Win8x4Pass1RgbShaderDef.h"
#include "RetroArch\nnedi3\shaders\Nnedi3ShadersNnedi3Nns64Win8x4Pass2RgbShaderDef.h"
#include "RetroArch\ntsc\shaders\artifact-colors\NtscShadersArtifactColorsArtifactColors0ShaderDef.h"
#include "RetroArch\ntsc\shaders\artifact-colors\NtscShadersArtifactColorsArtifactColors1ShaderDef.h"
#include "RetroArch\ntsc\shaders\artifact-colors\NtscShadersArtifactColorsArtifactColors2ShaderDef.h"
#include "RetroArch\ntsc\shaders\mame-ntsc\NtscShadersMameNtscMameNtscShaderDef.h"
#include "RetroArch\ntsc\shaders\mame-ntsc\NtscShadersMameNtscMamePostprocShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscGaussPassShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscStockShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass1Svideo3phaseShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass23phaseGammaShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass1Composite2phaseShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass22phaseShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass1Svideo2phaseShaderDef.h"
#include "RetroArch\ntsc\shaders\NtscShadersNtscPass22phaseGammaShaderDef.h"
#include "RetroArch\omniscale\shaders\OmniscaleShadersOmniscaleLegacyShaderDef.h"
#include "RetroArch\omniscale\shaders\OmniscaleShadersOmniscaleShaderDef.h"
#include "RetroArch\pal\shaders\PalShadersPalR57shellMoireOnlyShaderDef.h"
#include "RetroArch\pal\shaders\PalShadersPalR57shellShaderDef.h"
#include "RetroArch\pal\shaders\PalShadersPalSinglepassShaderDef.h"
#include "RetroArch\crt\shaders\guest\CrtShadersGuestAvgLum0ShaderDef.h"
#include "RetroArch\misc\MiscGradeShaderDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTMultiLUTShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleScanlinesVerticalInterlacingShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleBloomApproxShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleMaskResizeVerticalShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleMaskResizeHorizontalShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleScanlinesHorizontalApplyMaskShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleBrightpassShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleBloomVerticalShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleBloomHorizontalReconstituteShaderDef.h"
#include "RetroArch\crt\shaders\crt-royale\src\CrtShadersCrtRoyaleSrcCrtRoyaleGeometryAaLastPassShaderDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTLUTShaderDef.h"
#include "RetroArch\border\shaders\BorderShadersImgborderShaderDef.h"
#include "RetroArch\scanlines\shaders\ScanlinesShadersScanlineShaderDef.h"
#include "RetroArch\sharpen\shaders\SharpenShadersFastSharpenShaderDef.h"
#include "RetroArch\misc\MiscColorimetryShaderDef.h"
#include "RetroArch\handheld\shaders\color\HandheldShadersColorGbaColorShaderDef.h"
#include "RetroArch\handheld\shaders\HandheldShadersRetroV2ShaderDef.h"
#include "RetroArch\handheld\shaders\color\HandheldShadersColorGbcColorShaderDef.h"
#include "RetroArch\handheld\shaders\color\HandheldShadersColorNdsColorShaderDef.h"
#include "RetroArch\handheld\shaders\color\HandheldShadersColorPspColorShaderDef.h"
#include "RetroArch\handheld\shaders\color\HandheldShadersColorVbaColorShaderDef.h"
#include "RetroArch\scalefx\shaders\ScalefxShadersScalefxPass0ShaderDef.h"
#include "RetroArch\scalefx\shaders\ScalefxShadersScalefxPass1ShaderDef.h"
#include "RetroArch\scalefx\shaders\ScalefxShadersScalefxPass2ShaderDef.h"
#include "RetroArch\scalefx\shaders\ScalefxShadersScalefxPass3ShaderDef.h"
#include "RetroArch\scalefx\shaders\ScalefxShadersScalefxPass4ShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\reverse-aa-post3x\AntiAliasingShadersReverseAaPost3xReverseAaPost3xPass0ShaderDef.h"
#include "RetroArch\anti-aliasing\shaders\reverse-aa-post3x\AntiAliasingShadersReverseAaPost3xReverseAaPost3xPass1ShaderDef.h"
#include "RetroArch\deblur\shaders\DeblurShadersDeblurShaderDef.h"
#include "RetroArch\xsoft\shaders\XsoftShaders4xsoftShaderDef.h"
#include "RetroArch\scalefx\shaders\old\ScalefxShadersOldScalefxPass0ShaderDef.h"
#include "RetroArch\scalefx\shaders\old\ScalefxShadersOldScalefxPass1ShaderDef.h"
#include "RetroArch\scalefx\shaders\old\ScalefxShadersOldScalefxPass2ShaderDef.h"
#include "RetroArch\scalefx\shaders\old\ScalefxShadersOldScalefxPass3ShaderDef.h"
#include "RetroArch\scalefx\shaders\old\ScalefxShadersOldScalefxPass7ShaderDef.h"
#include "RetroArch\reshade\shaders\ReshadeShadersScanlinesShaderDef.h"
#include "RetroArch\reshade\shaders\ReshadeShadersBloomPassSh1nra358ShaderDef.h"
#include "RetroArch\blurs\BlursBlurGaussHShaderDef.h"
#include "RetroArch\blurs\BlursBlurGaussVShaderDef.h"
#include "RetroArch\reshade\shaders\ReshadeShadersBlurHazeSh1nra358ShaderDef.h"
#include "RetroArch\misc\MiscNtscColorsShaderDef.h"
#include "RetroArch\reshade\shaders\ReshadeShadersVibrancePassSh1nra358ShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersSnesHiresBlendShaderDef.h"
#include "RetroArch\misc\MiscInterlacingShaderDef.h"
#include "RetroArch\blurs\BlursSharpsmootherShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomBloomPass0ShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomBloomPass1ShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomBloomPass2ShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomBloomPass3ShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomBloomPass4ShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomLensFlarePass0ShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomLensFlarePass1ShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomLensFlarePass2ShaderDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomLightingCombineShaderDef.h"
#include "RetroArch\reshade\shaders\ReshadeShadersFilmGrainShaderDef.h"
#include "RetroArch\misc\MiscCmykHalftoneDotShaderDef.h"
#include "RetroArch\reshade\shaders\NormalsDisplacement\ReshadeShadersNormalsDisplacementNormalsDisplacementShaderDef.h"
#include "RetroArch\sabr\shaders\SabrShadersSabrHybridDeposterizeShaderDef.h"
#include "RetroArch\sabr\shaders\SabrShadersSabrV30ShaderDef.h"
#include "RetroArch\scalefx\shaders\ScalefxShadersScalefxPass4HybridShaderDef.h"
#include "RetroArch\scalehq\shaders\ScalehqShaders2xScaleHQShaderDef.h"
#include "RetroArch\scalehq\shaders\ScalehqShaders4xScaleHQShaderDef.h"
#include "RetroArch\scalenx\shaders\ScalenxShadersScale2xShaderDef.h"
#include "RetroArch\scalenx\shaders\ScalenxShadersScale2xplusShaderDef.h"
#include "RetroArch\scalenx\shaders\ScalenxShadersScale2xSFXShaderDef.h"
#include "RetroArch\scalenx\shaders\ScalenxShadersScale3xShaderDef.h"
#include "RetroArch\sharpen\shaders\SharpenShadersAdaptiveSharpenPass1ShaderDef.h"
#include "RetroArch\sharpen\shaders\SharpenShadersAdaptiveSharpenPass2ShaderDef.h"
#include "RetroArch\sharpen\shaders\SharpenShadersDiffShaderDef.h"
#include "RetroArch\sharpen\shaders\SharpenShadersSuperResExShaderDef.h"
#include "RetroArch\misc\MiscDeposterizePass0ShaderDef.h"
#include "RetroArch\misc\MiscDeposterizePass1ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrCustomJinc2SharperShaderDef.h"
#include "RetroArch\test\TestFeedbackNoncausalShaderDef.h"
#include "RetroArch\test\TestFeedbackShaderDef.h"
#include "RetroArch\test\TestFormatShaderDef.h"
#include "RetroArch\test\TestFrame_countShaderDef.h"
#include "RetroArch\test\TestHistoryShaderDef.h"
#include "RetroArch\test\TestPragmaNameShaderDef.h"
#include "RetroArch\vhs\shaders\gristleVHS\VhsShadersGristleVHSHorizontalSoftenShaderDef.h"
#include "RetroArch\blurs\sunset_gaussian\BlursSunset_gaussianSunset_horzShaderDef.h"
#include "RetroArch\vhs\shaders\gristleVHS\VhsShadersGristleVHSVHSShaderDef.h"
#include "RetroArch\vhs\shaders\VhsShadersMudlordPalVhsShaderDef.h"
#include "RetroArch\vhs\shaders\VhsShadersStaticShaderDef.h"
#include "RetroArch\vhs\shaders\VHSPro\VhsShadersVHSProVHSPro_ThirdShaderDef.h"
#include "RetroArch\vhs\shaders\VHSPro\VhsShadersVHSProVHSPro_TapeShaderDef.h"
#include "RetroArch\vhs\shaders\vhs_mpalko\VhsShadersVhs_mpalkoVhs_mpalko_pass0ShaderDef.h"
#include "RetroArch\vhs\shaders\vhs_mpalko\VhsShadersVhs_mpalkoVhs_mpalko_pass1ShaderDef.h"
#include "RetroArch\windowed\shaders\WindowedShadersLanczos16ShaderDef.h"
#include "RetroArch\xbr\shaders\2xBR-multipass\XbrShaders2xBRMultipass2xbrLv1CPass0ShaderDef.h"
#include "RetroArch\xbr\shaders\2xBR-multipass\XbrShaders2xBRMultipass2xbrLv1CPass1ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper4xbr3dPass0ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper4xbr3dPass1ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper4xbr3dPass2ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper4xbr3dPass3ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper4xbr3dPass1fShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper4xbr3dPass3fShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper8xbr3dPass0ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper8xbr3dPass1ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper8xbr3dPass2ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper8xbr3dPass3ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper8xbr3dPass4ShaderDef.h"
#include "RetroArch\xbr\shaders\super-xbr\XbrShadersSuperXbrSuper8xbr3dPass5ShaderDef.h"
#include "RetroArch\xbr\shaders\xbr-hybrid\XbrShadersXbrHybrid2xbrHybridV5GammaShaderDef.h"
#include "RetroArch\xbr\shaders\XbrShadersXbrLv23dShaderDef.h"
#include "RetroArch\xbr\shaders\XbrShadersXbrLv2ShaderDef.h"
#include "RetroArch\xbr\shaders\xbr-lv3-multipass\XbrShadersXbrLv3MultipassXbrLv3Pass0ShaderDef.h"
#include "RetroArch\xbr\shaders\xbr-lv3-multipass\XbrShadersXbrLv3MultipassXbrLv3Pass1ShaderDef.h"
#include "RetroArch\xbr\shaders\XbrShadersXbrLv3ShaderDef.h"
#include "RetroArch\xbr\shaders\xbr-mlv4-multipass\XbrShadersXbrMlv4MultipassXbrMlv4Pass1ShaderDef.h"
#include "RetroArch\xbr\shaders\xbr-mlv4-multipass\XbrShadersXbrMlv4MultipassXbrMlv4Pass2ShaderDef.h"
#include "RetroArch\xbr\shaders\xbr-mlv4-multipass\XbrShadersXbrMlv4MultipassXbrMlv4Pass3ShaderDef.h"
#include "RetroArch\xbr\shaders\xbr-mlv4-multipass\XbrShadersXbrMlv4MultipassXbrMlv4Pass4ShaderDef.h"
#include "RetroArch\xbrz\shaders\XbrzShaders4xbrzShaderDef.h"
#include "RetroArch\xbrz\shaders\XbrzShaders5xbrzShaderDef.h"
#include "RetroArch\xbrz\shaders\XbrzShaders6xbrzShaderDef.h"
#include "RetroArch\xbrz\shaders\XbrzShadersXbrzFreescalePass0ShaderDef.h"
#include "RetroArch\xbrz\shaders\XbrzShadersXbrzFreescalePass1ShaderDef.h"
#include "RetroArch\xbrz\shaders\XbrzShadersXbrzFreescaleShaderDef.h"
#include "RetroArch\xsal\shaders\XsalShaders2xsalLevel2ShaderDef.h"
#include "RetroArch\crt\shaders\CrtShadersDotmaskShaderDef.h"
#include "RetroArch\xsal\shaders\XsalShaders2xsalShaderDef.h"
#include "RetroArch\xsal\shaders\XsalShaders2xsalLevel2Pass2ShaderDef.h"
#include "RetroArch\xsal\shaders\XsalShaders2xsalLevel2HqShaderDef.h"
#include "RetroArch\xsoft\shaders\XsoftShaders4xsoftSdBShaderDef.h"
// %SHADER_INCLUDE%

#include "RetroArch\anti-aliasing\shaders\smaa\AntiAliasingShadersSmaaAreaTexTextureDef.h"
#include "RetroArch\anti-aliasing\shaders\smaa\AntiAliasingShadersSmaaSearchTexTextureDef.h"
#include "RetroArch\crt\shaders\guest\lut\CrtShadersGuestLutSony_trinitron1TextureDef.h"
#include "RetroArch\crt\shaders\guest\lut\CrtShadersGuestLutSony_trinitron2TextureDef.h"
#include "RetroArch\crt\shaders\guest\lut\CrtShadersGuestLutOther1TextureDef.h"
#include "RetroArch\crt\shaders\crt-potato\resources\CrtShadersCrtPotatoResourcesCrtPotatoThinTextureDef.h"
#include "RetroArch\crt\shaders\crt-potato\resources\CrtShadersCrtPotatoResourcesCrtPotatoThickTextureDef.h"
#include "RetroArch\reshade\shaders\blendoverlay\ReshadeShadersBlendoverlayShadowmask4x4TextureDef.h"
#include "RetroArch\crt\shaders\crtsim\CrtShadersCrtsimArtifactsTextureDef.h"
#include "RetroArch\crt\shaders\crtsim\CrtShadersCrtsimMaskTextureDef.h"
#include "RetroArch\crt\shaders\GritsScanlines\CrtShadersGritsScanlinesScanlineLUT4pxTextureDef.h"
#include "RetroArch\crt\shaders\GritsScanlines\CrtShadersGritsScanlinesTrinitron_colorTextureDef.h"
#include "RetroArch\crt\shaders\GritsScanlines\CrtShadersGritsScanlinesFakeSelfIlluminationTextureDef.h"
#include "RetroArch\crt\shaders\mame_hlsl\resources\CrtShadersMame_hlslResourcesApertureGrilleTextureDef.h"
#include "RetroArch\crt\shaders\metacrt\CrtShadersMetacrtBasilicaTextureDef.h"
#include "RetroArch\crt\shaders\metacrt\CrtShadersMetacrtWoodgrainTextureDef.h"
#include "RetroArch\crt\shaders\newpixie\CrtShadersNewpixieCrtframeTextureDef.h"
#include "RetroArch\crt\shaders\phosphorlut\luts\CrtShadersPhosphorlutLutsShadowmaskTextureDef.h"
#include "RetroArch\crt\shaders\phosphorlut\luts\CrtShadersPhosphorlutLutsApertureGrilleTextureDef.h"
#include "RetroArch\crt\shaders\phosphorlut\luts\CrtShadersPhosphorlutLutsSlotmaskTextureDef.h"
#include "RetroArch\hqx\resources\HqxResourcesHq2xTextureDef.h"
#include "RetroArch\hqx\resources\HqxResourcesHq3xTextureDef.h"
#include "RetroArch\hqx\resources\HqxResourcesHq4xTextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUT16TextureDef.h"
#include "RetroArch\nes_raw_palette\shaders\gtu-famicom\Nes_raw_paletteShadersGtuFamicomNesTableTextureDef.h"
#include "RetroArch\pal\resources\PalResourcesNes_lutTextureDef.h"
#include "RetroArch\crt\shaders\crt-royale\CrtShadersCrtRoyaleTileableLinearApertureGrille15Wide8And5d5SpacingResizeTo64TextureDef.h"
#include "RetroArch\crt\shaders\crt-royale\CrtShadersCrtRoyaleTileableLinearApertureGrille15Wide8And5d5SpacingTextureDef.h"
#include "RetroArch\crt\shaders\crt-royale\CrtShadersCrtRoyaleTileableLinearSlotMaskTall15Wide9And4d5Horizontal9d14VerticalSpacingResizeTo64TextureDef.h"
#include "RetroArch\crt\shaders\crt-royale\CrtShadersCrtRoyaleTileableLinearSlotMaskTall15Wide9And4d5Horizontal9d14VerticalSpacingTextureDef.h"
#include "RetroArch\crt\shaders\crt-royale\CrtShadersCrtRoyaleTileableLinearShadowMaskEDPResizeTo64TextureDef.h"
#include "RetroArch\crt\shaders\crt-royale\CrtShadersCrtRoyaleTileableLinearShadowMaskEDPTextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTKurozumi_64_D65_Rec601TextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTKurozumi_64_D93_Rec601TextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTNEC_XM29plus_captureTextureDef.h"
#include "RetroArch\border\textures\BorderTexturesPvmTextureDef.h"
#include "RetroArch\reshade\shaders\blendoverlay\ReshadeShadersBlendoverlayGrayscale_slotmaskTextureDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomLensDBTextureDef.h"
#include "RetroArch\reshade\shaders\bloom\ReshadeShadersBloomLensSpriteTextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTBsnesTextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTGBATextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTCmyk16TextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTNDSTextureDef.h"
#include "RetroArch\reshade\shaders\NormalsDisplacement\ReshadeShadersNormalsDisplacementCurveNormalsTextureDef.h"
#include "RetroArch\reshade\shaders\LUT\ReshadeShadersLUTVBATextureDef.h"
#include "RetroArch\vhs\resources\VhsResourcesPlayTextureDef.h"
// %TEXTURE_INCLUDE%

#include "RetroArch\anti-aliasing\AntiAliasingAaShader40Level2PresetDef.h"
#include "RetroArch\anti-aliasing\AntiAliasingAaShader40PresetDef.h"
#include "RetroArch\anti-aliasing\AntiAliasingAdvancedAaPresetDef.h"
#include "RetroArch\anti-aliasing\AntiAliasingFxaaPresetDef.h"
#include "RetroArch\anti-aliasing\AntiAliasingReverseAaPresetDef.h"
#include "RetroArch\anti-aliasing\AntiAliasingSmaaPresetDef.h"
#include "RetroArch\stock\StockBilinearPresetDef.h"
#include "RetroArch\blurs\BlursKawase_blur_5passPresetDef.h"
#include "RetroArch\blurs\BlursKawase_blur_9passPresetDef.h"
#include "RetroArch\blurs\BlursKawase_glowPresetDef.h"
#include "RetroArch\cel\CelAdvcartoonPresetDef.h"
#include "RetroArch\cel\CelMMJ_Cel_ShaderPresetDef.h"
#include "RetroArch\cel\CelMMJ_Cel_Shader_MPPresetDef.h"
#include "RetroArch\crt\CrtCrtAperturePresetDef.h"
#include "RetroArch\crt\CrtCrtCaligariPresetDef.h"
#include "RetroArch\crt\CrtCrtCgwgFastPresetDef.h"
#include "RetroArch\crt\CrtCrtEasymodeHalationPresetDef.h"
#include "RetroArch\crt\CrtCrtEasymodePresetDef.h"
#include "RetroArch\crt\CrtCrtFrutbunnPresetDef.h"
#include "RetroArch\crt\CrtCrtGeomDeluxePresetDef.h"
#include "RetroArch\crt\CrtCrtGeomPresetDef.h"
#include "RetroArch\crt\CrtCrtGuestDrVenomFastPresetDef.h"
#include "RetroArch\crt\CrtCrtGuestDrVenomPresetDef.h"
#include "RetroArch\crt\CrtCrtGuestSmPresetDef.h"
#include "RetroArch\crt\CrtCrtHyllian3dPresetDef.h"
#include "RetroArch\crt\CrtCrtHyllianGlowPresetDef.h"
#include "RetroArch\crt\CrtCrtHyllianMultipassPresetDef.h"
#include "RetroArch\crt\CrtCrtHyllianPresetDef.h"
#include "RetroArch\crt\CrtCrtInterlacedHalationPresetDef.h"
#include "RetroArch\crt\CrtCrtLottesFastPresetDef.h"
#include "RetroArch\crt\CrtCrtLottesMultipassGlowPresetDef.h"
#include "RetroArch\crt\CrtCrtLottesMultipassInterlacedGlowPresetDef.h"
#include "RetroArch\crt\CrtCrtLottesMultipassPresetDef.h"
#include "RetroArch\crt\CrtCrtLottesPresetDef.h"
#include "RetroArch\crt\CrtCrtMattiasPresetDef.h"
#include "RetroArch\crt\CrtCrtNesMiniPresetDef.h"
#include "RetroArch\crt\CrtCrtPiPresetDef.h"
#include "RetroArch\crt\CrtCrtPotatoCoolPresetDef.h"
#include "RetroArch\crt\CrtCrtPotatoWarmPresetDef.h"
#include "RetroArch\crt\CrtCrtTorridgristlePresetDef.h"
#include "RetroArch\crt\CrtCrtglow_gaussPresetDef.h"
#include "RetroArch\crt\CrtCrtglow_gauss_ntscPresetDef.h"
#include "RetroArch\crt\CrtCrtglow_lanczosPresetDef.h"
#include "RetroArch\crt\CrtCrtsimPresetDef.h"
#include "RetroArch\crt\CrtFakelottesPresetDef.h"
#include "RetroArch\crt\CrtGritsScanlinesPresetDef.h"
#include "RetroArch\crt\CrtGtuV050PresetDef.h"
#include "RetroArch\crt\CrtMame_hlslPresetDef.h"
#include "RetroArch\crt\CrtMetacrtPresetDef.h"
#include "RetroArch\crt\CrtNewpixieCrtPresetDef.h"
#include "RetroArch\crt\CrtPhosphorlutPresetDef.h"
#include "RetroArch\crt\CrtTvoutTweaksPresetDef.h"
#include "RetroArch\crt\CrtVectorGlowAltRenderPresetDef.h"
#include "RetroArch\crt\CrtVectorGlowPresetDef.h"
#include "RetroArch\crt\CrtVt220PresetDef.h"
#include "RetroArch\crt\CrtYee64PresetDef.h"
#include "RetroArch\crt\CrtYeetronPresetDef.h"
#include "RetroArch\crt\CrtZfastCrtPresetDef.h"
#include "RetroArch\cubic\CubicBicubicPresetDef.h"
#include "RetroArch\cubic\CubicCubicGammaCorrectPresetDef.h"
#include "RetroArch\cubic\CubicCubicPresetDef.h"
#include "RetroArch\ddt\DdtDdtPresetDef.h"
#include "RetroArch\denoisers\DenoisersCrtFastBilateralSuperXbrPresetDef.h"
#include "RetroArch\denoisers\DenoisersFastBilateralSuper2xbr3d3pPresetDef.h"
#include "RetroArch\denoisers\DenoisersFastBilateralSuperXbr4pPresetDef.h"
#include "RetroArch\denoisers\DenoisersFastBilateralSuperXbr6pPresetDef.h"
#include "RetroArch\denoisers\DenoisersFastBilateralSuperXbrNaturalVisionPresetDef.h"
#include "RetroArch\denoisers\DenoisersFastBilateralSuperXbrPresetDef.h"
#include "RetroArch\denoisers\DenoisersFastBilateralPresetDef.h"
#include "RetroArch\denoisers\DenoisersMedian_3x3PresetDef.h"
#include "RetroArch\denoisers\DenoisersMedian_5x5PresetDef.h"
#include "RetroArch\denoisers\DenoisersSlowBilateralPresetDef.h"
#include "RetroArch\dithering\DitheringBayerMatrixDitheringPresetDef.h"
#include "RetroArch\dithering\DitheringCbod_v1PresetDef.h"
#include "RetroArch\dithering\DitheringGdaptPresetDef.h"
#include "RetroArch\dithering\DitheringGenditherPresetDef.h"
#include "RetroArch\dithering\DitheringMdaptPresetDef.h"
#include "RetroArch\dithering\DitheringPs1DeditherBoxblurPresetDef.h"
#include "RetroArch\dithering\DitheringPs1DeditherComparisonPresetDef.h"
#include "RetroArch\dithering\DitheringPs1DitherPresetDef.h"
#include "RetroArch\eagle\EagleSupereaglePresetDef.h"
#include "RetroArch\gpu\Gpu3dfx_4x1PresetDef.h"
#include "RetroArch\gpu\GpuPowervr2PresetDef.h"
#include "RetroArch\gpu\shaders\3dfx\old\GpuShaders3dfxOld3dfx_4x1PresetDef.h"
#include "RetroArch\hqx\HqxHq2xHalphonPresetDef.h"
#include "RetroArch\hqx\HqxHq2xPresetDef.h"
#include "RetroArch\hqx\HqxHq3xPresetDef.h"
#include "RetroArch\hqx\HqxHq4xPresetDef.h"
#include "RetroArch\interpolation\InterpolationAannPresetDef.h"
#include "RetroArch\interpolation\InterpolationBandlimitPixelPresetDef.h"
#include "RetroArch\interpolation\InterpolationControlled_sharpnessPresetDef.h"
#include "RetroArch\interpolation\InterpolationGridBlendHybridPresetDef.h"
#include "RetroArch\interpolation\InterpolationPixellatePresetDef.h"
#include "RetroArch\interpolation\InterpolationQuilezPresetDef.h"
#include "RetroArch\interpolation\InterpolationSharpBilinear2xPrescalePresetDef.h"
#include "RetroArch\interpolation\InterpolationSharpBilinearScanlinesPresetDef.h"
#include "RetroArch\interpolation\InterpolationSharpBilinearSimplePresetDef.h"
#include "RetroArch\interpolation\InterpolationSharpBilinearPresetDef.h"
#include "RetroArch\interpolation\InterpolationSmootheststepPresetDef.h"
#include "RetroArch\interpolation\InterpolationSmuberstepPresetDef.h"
#include "RetroArch\linear\LinearLinearGammaCorrectPresetDef.h"
#include "RetroArch\misc\MiscImg_modPresetDef.h"
#include "RetroArch\motion-interpolation\MotionInterpolationMotion_interpolationPresetDef.h"
#include "RetroArch\motionblur\MotionblurFeedbackPresetDef.h"
#include "RetroArch\motionblur\MotionblurMix_framesPresetDef.h"
#include "RetroArch\motionblur\MotionblurMix_frames_smartPresetDef.h"
#include "RetroArch\motionblur\MotionblurMotionblurBluePresetDef.h"
#include "RetroArch\motionblur\MotionblurMotionblurColorPresetDef.h"
#include "RetroArch\motionblur\MotionblurMotionblurSimplePresetDef.h"
#include "RetroArch\motionblur\MotionblurResponseTimePresetDef.h"
#include "RetroArch\stock\StockNearestPresetDef.h"
#include "RetroArch\nedi\NediFastBilateralNediPresetDef.h"
#include "RetroArch\nedi\NediNediPresetDef.h"
#include "RetroArch\nedi\presets\NediPresetsBilateralVariant2PresetDef.h"
#include "RetroArch\nes_raw_palette\Nes_raw_paletteCgwgFamicomGeomPresetDef.h"
#include "RetroArch\nes_raw_palette\Nes_raw_paletteGtuFamicomPresetDef.h"
#include "RetroArch\nes_raw_palette\Nes_raw_paletteNtscNesPresetDef.h"
#include "RetroArch\nnedi3\Nnedi3Nnedi3Nns162xLumaPresetDef.h"
#include "RetroArch\nnedi3\Nnedi3Nnedi3Nns162xRgbPresetDef.h"
#include "RetroArch\nnedi3\Nnedi3Nnedi3Nns164xLumaPresetDef.h"
#include "RetroArch\nnedi3\Nnedi3Nnedi3Nns322xRgbNns324xLumaPresetDef.h"
#include "RetroArch\nnedi3\Nnedi3Nnedi3Nns324xRgbPresetDef.h"
#include "RetroArch\nnedi3\Nnedi3Nnedi3Nns642xNns324xNns168xRgbPresetDef.h"
#include "RetroArch\nnedi3\Nnedi3Nnedi3Nns642xNns324xRgbPresetDef.h"
#include "RetroArch\ntsc\NtscArtifactColorsPresetDef.h"
#include "RetroArch\ntsc\NtscMameNtscPresetDef.h"
#include "RetroArch\ntsc\NtscNtsc256pxGaussScanlinePresetDef.h"
#include "RetroArch\ntsc\NtscNtsc256pxSvideoGaussScanlinePresetDef.h"
#include "RetroArch\ntsc\NtscNtsc256pxSvideoPresetDef.h"
#include "RetroArch\ntsc\NtscNtsc256pxPresetDef.h"
#include "RetroArch\ntsc\NtscNtsc320pxGaussScanlinePresetDef.h"
#include "RetroArch\ntsc\NtscNtsc320pxSvideoGaussScanlinePresetDef.h"
#include "RetroArch\ntsc\NtscNtsc320pxSvideoPresetDef.h"
#include "RetroArch\ntsc\NtscNtsc320pxPresetDef.h"
#include "RetroArch\ntsc\NtscNtscAdaptivePresetDef.h"
#include "RetroArch\ntsc\NtscNtscSvideoPresetDef.h"
#include "RetroArch\ntsc\NtscNtscPresetDef.h"
#include "RetroArch\omniscale\OmniscaleOmniscaleLegacyPresetDef.h"
#include "RetroArch\omniscale\OmniscaleOmniscalePresetDef.h"
#include "RetroArch\pal\PalPalR57shellMoireOnlyPresetDef.h"
#include "RetroArch\pal\PalPalR57shellPresetDef.h"
#include "RetroArch\pal\PalPalSinglepassPresetDef.h"
#include "RetroArch\presets\PresetsC64MonitorPresetDef.h"
#include "RetroArch\presets\PresetsCrtGuestDrVenomKurozumiPresetDef.h"
#include "RetroArch\presets\PresetsCrtGuestDrVenomMaxDRPresetDef.h"
#include "RetroArch\presets\PresetsCrtGuestDrVenomNtscCompositeStockPresetDef.h"
#include "RetroArch\presets\PresetsCrtGuestDrVenomNtscCompositePresetDef.h"
#include "RetroArch\presets\PresetsCrtGuestDrVenomStockPresetDef.h"
#include "RetroArch\presets\PresetsCrtsimGrungyPresetDef.h"
#include "RetroArch\presets\PresetsImgborderRoyaleKurozumiPresetDef.h"
#include "RetroArch\presets\PresetsMdaptFastBilateralSuper4xbrScanlinesPresetDef.h"
#include "RetroArch\presets\PresetsNediPowervrSharpenPresetDef.h"
#include "RetroArch\presets\PresetsNesColorDecoderColorimetryPixellatePresetDef.h"
#include "RetroArch\presets\PresetsNesColorDecoderPixellatePresetDef.h"
#include "RetroArch\presets\PresetsNtscPhosphorlutPresetDef.h"
#include "RetroArch\presets\PresetsNtsclutPhosphorlutPresetDef.h"
#include "RetroArch\presets\PresetsRetroV2GbaColorPresetDef.h"
#include "RetroArch\presets\PresetsRetroV2GbcColorPresetDef.h"
#include "RetroArch\presets\PresetsRetroV2ImageAdjustmentPresetDef.h"
#include "RetroArch\presets\PresetsRetroV2NdsColorPresetDef.h"
#include "RetroArch\presets\PresetsRetroV2PspColorPresetDef.h"
#include "RetroArch\presets\PresetsRetroV2VbaColorPresetDef.h"
#include "RetroArch\presets\PresetsScalefxRAAAaFastPresetDef.h"
#include "RetroArch\presets\PresetsScalefxRAAAaPresetDef.h"
#include "RetroArch\presets\PresetsScalefxAaFastPresetDef.h"
#include "RetroArch\presets\PresetsScalefxAaPresetDef.h"
#include "RetroArch\presets\PresetsScalefx9AaBlurHazyNtscSh1nra358PresetDef.h"
#include "RetroArch\presets\PresetsScalefx9AaBlurHazyVibranceSh1nra358PresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNesColorDecoderPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtsc256pxCompositePresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtsc256pxSvideoPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtsc2phaseCompositePresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtsc2phaseSvideoPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtsc320pxCompositePresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtsc320pxSvideoPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtsc3phaseCompositePresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtsc3phaseSvideoPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutNtscNesPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutSnesHiresBlendPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutJincSharpenPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutPixelsharpPresetDef.h"
#include "RetroArch\presets\tvout\PresetsTvoutTvoutPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNesColorDecoderInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtsc256pxCompositeInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtsc256pxSvideoInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtsc2phaseCompositeInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtsc2phaseSvideoInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtsc320pxCompositeInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtsc320pxSvideoInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtsc3phaseCompositeInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtsc3phaseSvideoInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutNtscNesInterlacingPresetDef.h"
#include "RetroArch\presets\tvout+interlacing\PresetsTvoutInterlacingTvoutJincSharpenInterlacingPresetDef.h"
#include "RetroArch\presets\PresetsXsoftScalefxLevel2aaSharpsmootherPresetDef.h"
#include "RetroArch\presets\PresetsXsoftScalefxLevel2aaPresetDef.h"
#include "RetroArch\reshade\ReshadeBlendoverlayPresetDef.h"
#include "RetroArch\reshade\ReshadeBloomPresetDef.h"
#include "RetroArch\reshade\ReshadeBsnesGammaRampPresetDef.h"
#include "RetroArch\reshade\ReshadeFilmGrainPresetDef.h"
#include "RetroArch\reshade\ReshadeGbaPresetDef.h"
#include "RetroArch\reshade\ReshadeHalftonePrintPresetDef.h"
#include "RetroArch\reshade\ReshadeLutPresetDef.h"
#include "RetroArch\reshade\ReshadeNdsPresetDef.h"
#include "RetroArch\reshade\ReshadeNormalsDisplacementPresetDef.h"
#include "RetroArch\reshade\ReshadeVbaPresetDef.h"
#include "RetroArch\sabr\SabrSabrHybridDeposterizePresetDef.h"
#include "RetroArch\sabr\SabrSabrPresetDef.h"
#include "RetroArch\scalefx\ScalefxScalefxRAAPresetDef.h"
#include "RetroArch\scalefx\ScalefxScalefx9xPresetDef.h"
#include "RetroArch\scalefx\ScalefxScalefxHybridPresetDef.h"
#include "RetroArch\scalefx\ScalefxScalefxPresetDef.h"
#include "RetroArch\scalefx\shaders\old\ScalefxShadersOldScalefx9xPresetDef.h"
#include "RetroArch\scalefx\shaders\old\ScalefxShadersOldScalefxPresetDef.h"
#include "RetroArch\scalehq\Scalehq2xScaleHQPresetDef.h"
#include "RetroArch\scalehq\Scalehq4xScaleHQPresetDef.h"
#include "RetroArch\scalenx\ScalenxScale2xPresetDef.h"
#include "RetroArch\scalenx\ScalenxScale2xplusPresetDef.h"
#include "RetroArch\scalenx\ScalenxScale2xSFXPresetDef.h"
#include "RetroArch\scalenx\ScalenxScale3xPresetDef.h"
#include "RetroArch\sharpen\SharpenAdaptiveSharpenMultipassPresetDef.h"
#include "RetroArch\sharpen\SharpenAdaptiveSharpenPresetDef.h"
#include "RetroArch\sharpen\SharpenSuperXbrSuperResPresetDef.h"
#include "RetroArch\test\TestFeedbackNoncausalPresetDef.h"
#include "RetroArch\test\TestFeedbackPresetDef.h"
#include "RetroArch\test\TestFrame_countPresetDef.h"
#include "RetroArch\test\TestHistoryPresetDef.h"
#include "RetroArch\test\TestPragmaNamePresetDef.h"
#include "RetroArch\vhs\VhsGristleVHSPresetDef.h"
#include "RetroArch\vhs\VhsMudlordPalVhsPresetDef.h"
#include "RetroArch\vhs\VhsNtscVcrPresetDef.h"
#include "RetroArch\windowed\WindowedJinc2SharpPresetDef.h"
#include "RetroArch\windowed\WindowedJinc2SharperPresetDef.h"
#include "RetroArch\windowed\WindowedJinc2PresetDef.h"
#include "RetroArch\windowed\WindowedLanczos16PresetDef.h"
#include "RetroArch\xbr\Xbr2xBRLv1MultipassPresetDef.h"
#include "RetroArch\xbr\XbrSuper2xbr3d2pPresetDef.h"
#include "RetroArch\xbr\XbrSuper2xbr3d3pSmootherPresetDef.h"
#include "RetroArch\xbr\XbrSuper4xbr3d4pPresetDef.h"
#include "RetroArch\xbr\XbrSuper4xbr3d6pSmootherPresetDef.h"
#include "RetroArch\xbr\XbrSuper8xbr3d6pPresetDef.h"
#include "RetroArch\xbr\XbrSuperXbr2pPresetDef.h"
#include "RetroArch\xbr\XbrSuperXbr3pSmootherPresetDef.h"
#include "RetroArch\xbr\XbrSuperXbr6pAdaptivePresetDef.h"
#include "RetroArch\xbr\XbrSuperXbr6pSmallDetailsPresetDef.h"
#include "RetroArch\xbr\XbrSuperXbr6pPresetDef.h"
#include "RetroArch\xbr\XbrSuperXbrDeposterizePresetDef.h"
#include "RetroArch\xbr\XbrXbrHybridPresetDef.h"
#include "RetroArch\xbr\XbrXbrLv23dPresetDef.h"
#include "RetroArch\xbr\XbrXbrLv2PresetDef.h"
#include "RetroArch\xbr\XbrXbrLv3MultipassPresetDef.h"
#include "RetroArch\xbr\XbrXbrLv3PresetDef.h"
#include "RetroArch\xbr\XbrXbrMlv4MultipassPresetDef.h"
#include "RetroArch\xbrz\Xbrz4xbrzLinearPresetDef.h"
#include "RetroArch\xbrz\Xbrz5xbrzLinearPresetDef.h"
#include "RetroArch\xbrz\Xbrz6xbrzLinearPresetDef.h"
#include "RetroArch\xbrz\XbrzXbrzFreescaleMultipassPresetDef.h"
#include "RetroArch\xbrz\XbrzXbrzFreescalePresetDef.h"
#include "RetroArch\xsal\Xsal2xsalLevel2CrtPresetDef.h"
#include "RetroArch\xsal\Xsal2xsalPresetDef.h"
#include "RetroArch\xsal\Xsal4xsalLevel2CrtPresetDef.h"
#include "RetroArch\xsal\Xsal4xsalLevel2HqPresetDef.h"
#include "RetroArch\xsal\Xsal4xsalLevel2PresetDef.h"
#include "RetroArch\xsoft\Xsoft4xsoftPresetDef.h"
#include "RetroArch\xsoft\Xsoft4xsoftSdBPresetDef.h"
// %PRESET_INCLUDE%

namespace RetroArch
{
const static std::vector<PresetDef*> PresetList = {
new AntiAliasingAaShader40Level2PresetDef(),
new AntiAliasingAaShader40PresetDef(),
new AntiAliasingAdvancedAaPresetDef(),
new AntiAliasingFxaaPresetDef(),
new AntiAliasingReverseAaPresetDef(),
new AntiAliasingSmaaPresetDef(),
new StockBilinearPresetDef(),
new BlursKawase_blur_5passPresetDef(),
new BlursKawase_blur_9passPresetDef(),
new BlursKawase_glowPresetDef(),
new CelAdvcartoonPresetDef(),
new CelMMJ_Cel_ShaderPresetDef(),
new CelMMJ_Cel_Shader_MPPresetDef(),
new CrtCrtAperturePresetDef(),
new CrtCrtCaligariPresetDef(),
new CrtCrtCgwgFastPresetDef(),
new CrtCrtEasymodeHalationPresetDef(),
new CrtCrtEasymodePresetDef(),
new CrtCrtFrutbunnPresetDef(),
new CrtCrtGeomDeluxePresetDef(),
new CrtCrtGeomPresetDef(),
new CrtCrtGuestDrVenomFastPresetDef(),
new CrtCrtGuestDrVenomPresetDef(),
new CrtCrtGuestSmPresetDef(),
new CrtCrtHyllian3dPresetDef(),
new CrtCrtHyllianGlowPresetDef(),
new CrtCrtHyllianMultipassPresetDef(),
new CrtCrtHyllianPresetDef(),
new CrtCrtInterlacedHalationPresetDef(),
new CrtCrtLottesFastPresetDef(),
new CrtCrtLottesMultipassGlowPresetDef(),
new CrtCrtLottesMultipassInterlacedGlowPresetDef(),
new CrtCrtLottesMultipassPresetDef(),
new CrtCrtLottesPresetDef(),
new CrtCrtMattiasPresetDef(),
new CrtCrtNesMiniPresetDef(),
new CrtCrtPiPresetDef(),
new CrtCrtPotatoCoolPresetDef(),
new CrtCrtPotatoWarmPresetDef(),
new CrtCrtTorridgristlePresetDef(),
new CrtCrtglow_gaussPresetDef(),
new CrtCrtglow_gauss_ntscPresetDef(),
new CrtCrtglow_lanczosPresetDef(),
new CrtCrtsimPresetDef(),
new CrtFakelottesPresetDef(),
new CrtGritsScanlinesPresetDef(),
new CrtGtuV050PresetDef(),
new CrtMame_hlslPresetDef(),
new CrtMetacrtPresetDef(),
new CrtNewpixieCrtPresetDef(),
new CrtPhosphorlutPresetDef(),
new CrtTvoutTweaksPresetDef(),
new CrtVectorGlowAltRenderPresetDef(),
new CrtVectorGlowPresetDef(),
new CrtVt220PresetDef(),
new CrtYee64PresetDef(),
new CrtYeetronPresetDef(),
new CrtZfastCrtPresetDef(),
new CubicBicubicPresetDef(),
new CubicCubicGammaCorrectPresetDef(),
new CubicCubicPresetDef(),
new DdtDdtPresetDef(),
new DenoisersCrtFastBilateralSuperXbrPresetDef(),
new DenoisersFastBilateralSuper2xbr3d3pPresetDef(),
new DenoisersFastBilateralSuperXbr4pPresetDef(),
new DenoisersFastBilateralSuperXbr6pPresetDef(),
new DenoisersFastBilateralSuperXbrNaturalVisionPresetDef(),
new DenoisersFastBilateralSuperXbrPresetDef(),
new DenoisersFastBilateralPresetDef(),
new DenoisersMedian_3x3PresetDef(),
new DenoisersMedian_5x5PresetDef(),
new DenoisersSlowBilateralPresetDef(),
new DitheringBayerMatrixDitheringPresetDef(),
new DitheringCbod_v1PresetDef(),
new DitheringGdaptPresetDef(),
new DitheringGenditherPresetDef(),
new DitheringMdaptPresetDef(),
new DitheringPs1DeditherBoxblurPresetDef(),
new DitheringPs1DeditherComparisonPresetDef(),
new DitheringPs1DitherPresetDef(),
new EagleSupereaglePresetDef(),
new Gpu3dfx_4x1PresetDef(),
new GpuPowervr2PresetDef(),
new GpuShaders3dfxOld3dfx_4x1PresetDef(),
new HqxHq2xHalphonPresetDef(),
new HqxHq2xPresetDef(),
new HqxHq3xPresetDef(),
new HqxHq4xPresetDef(),
new InterpolationAannPresetDef(),
new InterpolationBandlimitPixelPresetDef(),
new InterpolationControlled_sharpnessPresetDef(),
new InterpolationGridBlendHybridPresetDef(),
new InterpolationPixellatePresetDef(),
new InterpolationQuilezPresetDef(),
new InterpolationSharpBilinear2xPrescalePresetDef(),
new InterpolationSharpBilinearScanlinesPresetDef(),
new InterpolationSharpBilinearSimplePresetDef(),
new InterpolationSharpBilinearPresetDef(),
new InterpolationSmootheststepPresetDef(),
new InterpolationSmuberstepPresetDef(),
new LinearLinearGammaCorrectPresetDef(),
new MiscImg_modPresetDef(),
new MotionInterpolationMotion_interpolationPresetDef(),
new MotionblurFeedbackPresetDef(),
new MotionblurMix_framesPresetDef(),
new MotionblurMix_frames_smartPresetDef(),
new MotionblurMotionblurBluePresetDef(),
new MotionblurMotionblurColorPresetDef(),
new MotionblurMotionblurSimplePresetDef(),
new MotionblurResponseTimePresetDef(),
new StockNearestPresetDef(),
new NediFastBilateralNediPresetDef(),
new NediNediPresetDef(),
new NediPresetsBilateralVariant2PresetDef(),
new Nes_raw_paletteCgwgFamicomGeomPresetDef(),
new Nes_raw_paletteGtuFamicomPresetDef(),
new Nes_raw_paletteNtscNesPresetDef(),
new Nnedi3Nnedi3Nns162xLumaPresetDef(),
new Nnedi3Nnedi3Nns162xRgbPresetDef(),
new Nnedi3Nnedi3Nns164xLumaPresetDef(),
new Nnedi3Nnedi3Nns322xRgbNns324xLumaPresetDef(),
new Nnedi3Nnedi3Nns324xRgbPresetDef(),
new Nnedi3Nnedi3Nns642xNns324xNns168xRgbPresetDef(),
new Nnedi3Nnedi3Nns642xNns324xRgbPresetDef(),
new NtscArtifactColorsPresetDef(),
new NtscMameNtscPresetDef(),
new NtscNtsc256pxGaussScanlinePresetDef(),
new NtscNtsc256pxSvideoGaussScanlinePresetDef(),
new NtscNtsc256pxSvideoPresetDef(),
new NtscNtsc256pxPresetDef(),
new NtscNtsc320pxGaussScanlinePresetDef(),
new NtscNtsc320pxSvideoGaussScanlinePresetDef(),
new NtscNtsc320pxSvideoPresetDef(),
new NtscNtsc320pxPresetDef(),
new NtscNtscAdaptivePresetDef(),
new NtscNtscSvideoPresetDef(),
new NtscNtscPresetDef(),
new OmniscaleOmniscaleLegacyPresetDef(),
new OmniscaleOmniscalePresetDef(),
new PalPalR57shellMoireOnlyPresetDef(),
new PalPalR57shellPresetDef(),
new PalPalSinglepassPresetDef(),
new PresetsC64MonitorPresetDef(),
new PresetsCrtGuestDrVenomKurozumiPresetDef(),
new PresetsCrtGuestDrVenomMaxDRPresetDef(),
new PresetsCrtGuestDrVenomNtscCompositeStockPresetDef(),
new PresetsCrtGuestDrVenomNtscCompositePresetDef(),
new PresetsCrtGuestDrVenomStockPresetDef(),
new PresetsCrtsimGrungyPresetDef(),
new PresetsImgborderRoyaleKurozumiPresetDef(),
new PresetsMdaptFastBilateralSuper4xbrScanlinesPresetDef(),
new PresetsNediPowervrSharpenPresetDef(),
new PresetsNesColorDecoderColorimetryPixellatePresetDef(),
new PresetsNesColorDecoderPixellatePresetDef(),
new PresetsNtscPhosphorlutPresetDef(),
new PresetsNtsclutPhosphorlutPresetDef(),
new PresetsRetroV2GbaColorPresetDef(),
new PresetsRetroV2GbcColorPresetDef(),
new PresetsRetroV2ImageAdjustmentPresetDef(),
new PresetsRetroV2NdsColorPresetDef(),
new PresetsRetroV2PspColorPresetDef(),
new PresetsRetroV2VbaColorPresetDef(),
new PresetsScalefxRAAAaFastPresetDef(),
new PresetsScalefxRAAAaPresetDef(),
new PresetsScalefxAaFastPresetDef(),
new PresetsScalefxAaPresetDef(),
new PresetsScalefx9AaBlurHazyNtscSh1nra358PresetDef(),
new PresetsScalefx9AaBlurHazyVibranceSh1nra358PresetDef(),
new PresetsTvoutTvoutNesColorDecoderPresetDef(),
new PresetsTvoutTvoutNtsc256pxCompositePresetDef(),
new PresetsTvoutTvoutNtsc256pxSvideoPresetDef(),
new PresetsTvoutTvoutNtsc2phaseCompositePresetDef(),
new PresetsTvoutTvoutNtsc2phaseSvideoPresetDef(),
new PresetsTvoutTvoutNtsc320pxCompositePresetDef(),
new PresetsTvoutTvoutNtsc320pxSvideoPresetDef(),
new PresetsTvoutTvoutNtsc3phaseCompositePresetDef(),
new PresetsTvoutTvoutNtsc3phaseSvideoPresetDef(),
new PresetsTvoutTvoutNtscNesPresetDef(),
new PresetsTvoutTvoutSnesHiresBlendPresetDef(),
new PresetsTvoutTvoutJincSharpenPresetDef(),
new PresetsTvoutTvoutPixelsharpPresetDef(),
new PresetsTvoutTvoutPresetDef(),
new PresetsTvoutInterlacingTvoutInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNesColorDecoderInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtsc256pxCompositeInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtsc256pxSvideoInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtsc2phaseCompositeInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtsc2phaseSvideoInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtsc320pxCompositeInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtsc320pxSvideoInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtsc3phaseCompositeInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtsc3phaseSvideoInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutNtscNesInterlacingPresetDef(),
new PresetsTvoutInterlacingTvoutJincSharpenInterlacingPresetDef(),
new PresetsXsoftScalefxLevel2aaSharpsmootherPresetDef(),
new PresetsXsoftScalefxLevel2aaPresetDef(),
new ReshadeBlendoverlayPresetDef(),
new ReshadeBloomPresetDef(),
new ReshadeBsnesGammaRampPresetDef(),
new ReshadeFilmGrainPresetDef(),
new ReshadeGbaPresetDef(),
new ReshadeHalftonePrintPresetDef(),
new ReshadeLutPresetDef(),
new ReshadeNdsPresetDef(),
new ReshadeNormalsDisplacementPresetDef(),
new ReshadeVbaPresetDef(),
new SabrSabrHybridDeposterizePresetDef(),
new SabrSabrPresetDef(),
new ScalefxScalefxRAAPresetDef(),
new ScalefxScalefx9xPresetDef(),
new ScalefxScalefxHybridPresetDef(),
new ScalefxScalefxPresetDef(),
new ScalefxShadersOldScalefx9xPresetDef(),
new ScalefxShadersOldScalefxPresetDef(),
new Scalehq2xScaleHQPresetDef(),
new Scalehq4xScaleHQPresetDef(),
new ScalenxScale2xPresetDef(),
new ScalenxScale2xplusPresetDef(),
new ScalenxScale2xSFXPresetDef(),
new ScalenxScale3xPresetDef(),
new SharpenAdaptiveSharpenMultipassPresetDef(),
new SharpenAdaptiveSharpenPresetDef(),
new SharpenSuperXbrSuperResPresetDef(),
new TestFeedbackNoncausalPresetDef(),
new TestFeedbackPresetDef(),
new TestFrame_countPresetDef(),
new TestHistoryPresetDef(),
new TestPragmaNamePresetDef(),
new VhsGristleVHSPresetDef(),
new VhsMudlordPalVhsPresetDef(),
new VhsNtscVcrPresetDef(),
new WindowedJinc2SharpPresetDef(),
new WindowedJinc2SharperPresetDef(),
new WindowedJinc2PresetDef(),
new WindowedLanczos16PresetDef(),
new Xbr2xBRLv1MultipassPresetDef(),
new XbrSuper2xbr3d2pPresetDef(),
new XbrSuper2xbr3d3pSmootherPresetDef(),
new XbrSuper4xbr3d4pPresetDef(),
new XbrSuper4xbr3d6pSmootherPresetDef(),
new XbrSuper8xbr3d6pPresetDef(),
new XbrSuperXbr2pPresetDef(),
new XbrSuperXbr3pSmootherPresetDef(),
new XbrSuperXbr6pAdaptivePresetDef(),
new XbrSuperXbr6pSmallDetailsPresetDef(),
new XbrSuperXbr6pPresetDef(),
new XbrSuperXbrDeposterizePresetDef(),
new XbrXbrHybridPresetDef(),
new XbrXbrLv23dPresetDef(),
new XbrXbrLv2PresetDef(),
new XbrXbrLv3MultipassPresetDef(),
new XbrXbrLv3PresetDef(),
new XbrXbrMlv4MultipassPresetDef(),
new Xbrz4xbrzLinearPresetDef(),
new Xbrz5xbrzLinearPresetDef(),
new Xbrz6xbrzLinearPresetDef(),
new XbrzXbrzFreescaleMultipassPresetDef(),
new XbrzXbrzFreescalePresetDef(),
new Xsal2xsalLevel2CrtPresetDef(),
new Xsal2xsalPresetDef(),
new Xsal4xsalLevel2CrtPresetDef(),
new Xsal4xsalLevel2HqPresetDef(),
new Xsal4xsalLevel2PresetDef(),
new Xsoft4xsoftPresetDef(),
new Xsoft4xsoftSdBPresetDef(),
// %PRESET_CLASS%
};
}
