cmake -S SPIRV-Cross -B Debug\SPIRV-Cross -GNinja -DCMAKE_BUILD_TYPE=Debug -DSPIRV_CROSS_ENABLE_GLSL=True -DSPIRV_CROSS_ENABLE_C_API=False -DSPIRV_CROSS_CLI=False -DSPIRV_CROSS_ENABLE_UTIL=False -DSPIRV_CROSS_ENABLE_MSL=False -DSPIRV_CROSS_ENABLE_TESTS=False
cmake --build Debug\SPIRV-Cross
