cmake -S glslang -B Release\glslang -G "Visual Studio 17 2022" -DENABLE_HLSL=False -DGLSLANG_TESTS=False -DENABLE_SPVREMAPPER=False -DGLSLANG_ENABLE_INSTALL=False -DENABLE_OPT=False -DBUILD_EXTERNAL=False -DENABLE_PCH=False -DENABLE_GLSLANG_BINARIES=False -DENABLE_EXCEPTIONS=False -DENABLE_RTTI=False -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE=../../../lib
cmake --build Release\glslang --config Release

