cmake -S SPIRV-Cross -B Debug\SPIRV-Cross -G "Visual Studio 17 2022" -DSPIRV_CROSS_ENABLE_GLSL=True -DSPIRV_CROSS_ENABLE_C_API=False -DSPIRV_CROSS_CLI=False -DSPIRV_CROSS_ENABLE_UTIL=False -DSPIRV_CROSS_ENABLE_MSL=False -DSPIRV_CROSS_ENABLE_TESTS=False -DSPIRV_CROSS_ENABLE_CPP=False
cmake --build Debug\SPIRV-Cross --config Debug

