cmake -S glslang -B Debug\glslang -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug -DENABLE_HLSL=False -DGLSLANG_TESTS=False -DENABLE_SPVREMAPPER=False -DGLSLANG_ENABLE_INSTALL=False -DENABLE_OPT=False -DBUILD_EXTERNAL=False -DENABLE_PCH=False -DENABLE_GLSLANG_BINARIES=False -DENABLE_EXCEPTIONS=TRue -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDebugDLL
cmake --build Debug\glslang
