name: Build Dependencies

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: windows-2022
    
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]

    steps:    
    - run: Get-PSDrive

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build glslang
      working-directory: ./Dependencies
      run: 'Build_glslang_${{ matrix.configuration }}.bat'
      shell: cmd

    - name: Build SPIRV-Cross
      working-directory: ./Dependencies
      run: 'Build_SPIRV-Cross_${{ matrix.configuration }}.bat'
      shell: cmd

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 'ShaderGlass_Dependencies_${{ matrix.platform }}_${{ matrix.configuration }}'
        path: |
          '.\\Dependencies\\${{ matrix.configuration }}\\glslang\\glslang\\*.lib'
          '.\\Dependencies\\${{ matrix.configuration }}\\SPIRV-Cross\\*.lib'
        overwrite: true
